### ISSUE TITLE
SourceMap not working with Angular 13

### ISSUE THREAD

**Issue by FazioNico** [chihab/ngx-env#11]
Hi! 
After try this package i see some problem with latest Angular version. There not have any sourcemap during serve in developpement mode. 
Did some one have this issue and/or have any solution to solve this trouble?
Thanks!

**Comment by chihab** [comment]
Hi,
Thanks for reporting the issue. It has been fixed on 2.0.1.

**Comment by FazioNico** [comment]
> Hi, Thanks for reporting the issue. It has been fixed on 2.0.1.

Thanks for fix!! Very nice and powerfull package 🙏🎉
