### ISSUE TITLE
ng test error: Data path "" should NOT have additional properties(configPath).

### ISSUE THREAD

**Issue by BrothersWar** [chihab/ngx-env#13]
package version: **1.1.0**
angular version: **11**
Error:
```
Schema validation failed with the following errors:   
Data path "" should NOT have additional properties(configPath).
```
Error occurs when i run command: ng test. I think it's because my angular.json missing some properties

**Comment by chihab** [comment]
Could you please tell me if you're getting the same issue when running this command?

`cd /tmp && V=11 && npx @angular/cli@$V new ng-app$V --defaults && cd ng-app$V && npx ng add @ngx-env/builder@1.1.0 && npm run test -- --watch=false`

The commands generates a new app using CLI v11, adds @ngx-env/builder v1.1.0 then runs tests on it.

**Comment by BrothersWar** [comment]
ye your command is working. what if i not need all properties from your angular.json. 
my test in angular.json: 
```
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "configPath": "jest.config.js"
          }
        },
```

**Comment by chihab** [comment]
You are not using `@ngx-env/builder` here :)
Right now `@ngx-env/builder` only supports CLI builders.
Could you copy/paste your `angular.json`  and the output you get on your Terminal here?

**Comment by chihab** [comment]
Closing the issue as not related to @ngx-env/builder.
