### ISSUE TITLE
long time recompilation

### ISSUE THREAD

**Issue by BrothersWar** [chihab/ngx-env#14]
When i use:
```
        "build": {
          "builder": "@ngx-env/builder:browser",
         }
```
instead of my:
```
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
         }
```
recompilation takes about a minute each time. 
in serve i can use: 
```
        "serve": {
          "builder": "@ngx-env/builder:dev-server",
         }
```
and everything okay. But i need to use builder to deploy my code to production. Any ideas? I tried on 1.1.0 version and 2.0.0 versions. Angular 11

**Comment by chihab** [comment]
Could you please put the outputs with and without `@ngx-env/builder` here?

**Comment by BrothersWar** [comment]
i add: 
```
              "buildOptimizer": false,
              "optimization": false,
```

to my:

```
 "configurations": {
            "development": {
              "statsJson": true,
              "sourceMap": true,
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "namedChunks": true,
              "extractLicenses": false
            },
```

and everything now works fine

**Comment by jperezruiz** [comment]
I also notice that, it optimizes the code but the default behavior of `@angular-devkit/build-angular:browser`. It is possible to match the default behavior of `@angular-devkit/build-angular:browser` for the different configurations?

**Comment by chihab** [comment]
Thanks for confirming the issue @jperezruiz. I was able to reproduce it on v11 with v1.1.0.
I am looking into it.

**Comment by jperezruiz** [comment]
Thank you! If I can help please tell me

**Comment by y4nnick** [comment]
Any update on this one?

**Comment by loclv** [comment]
When i develop with  _Hot Module Replacement_ mode, the recompiling is also much more slowly.

**Comment by chihab** [comment]
Closing the issue as this way for old v11 versions. Let me know if you still have it with newer Angular versions.

**Comment by jimyhdolores** [comment]
@chihab I am using the :
"@ngx-env/builder : "^15.2.1". 

When executing the command "ng test" it is super slow compared to "build-angular:karma".
