### ISSUE TITLE
Conflict with block-scoped @types/node on env.d.ts

### ISSUE THREAD

**Issue by stephane-tessier** [chihab/ngx-env#16]
Hi

I'd like to reopen https://github.com/chihab/ngx-env/issues/8

I have the same problem but I didn't understand the fix.

I have `src/env.d.ts`: 
```
declare let process: {
  env: {
    NG_APP_ENV: string;
    // Replace the line below with your environment variable for better type checking
    NG_APP_apiHost: string;
    NG_APP_apiURL: string;
  };
};
```

and when I run my linter: 
```sh
tsc --noEmit && eslint . --ext js,ts --quiet --fix
```

**"Cannot redeclare block-scoped variable 'process'."**

![image](https://user-images.githubusercontent.com/2227881/156405532-8a570e94-09c2-4ce3-bb37-12c77d036485.png)

**Comment by chihab** [comment]
Thanks for reporting that @stephane-tessier.

Could you please confirm that you don't have any issues with type checking on your editor nor on the CLI commands (ng serve...)?

**Comment by stephane-tessier** [comment]
Yes, I can confirm that. Everything works fine except the `tsc` cli

**Comment by chihab** [comment]
The only way I see to make it work with tsc is to update the tsconfig files generated by the CLI, something like `types: []` in `tsconfig.json` but not sure if that's the best/ a viable solution.

**Comment by stephane-tessier** [comment]
Not sure what you mean.

In my package.json I have: 
```json
    "@types/jasmine": "3.10.2",
    "@types/luxon": "2.0.7",
    "@types/node": "16.11.10",
```

So in tsconfig.json I tried to force jasmin and luxon:
```json
  "types": ["luxon", "jasmine"],
```
but it didn't solve the problem.

BUT if I declare the types directly in the cli args, it seems to do the trick :partying_face: 

```sh
tsc --noEmit --types jasmine,luxon && eslint . --ext js,ts --fix
```

It will do for now.
But if you have a cleaner solution let me know!
Thanks.
