### ISSUE TITLE
ERROR ReferenceError: process is not defined

### ISSUE THREAD

**Issue by bavaleakashGL** [chihab/ngx-env#17]
I always end up with this error
core.mjs:6485 ERROR ReferenceError: process is not defined
I am using Angular 13

**Comment by chihab** [comment]
Did you run the command `ng add @ngx-env/builder`?
Could you copy/paste your `angular.json` here?

**Comment by chihab** [comment]
Closing it.
Feel free to re-open the issue if you encounter it again.

**Comment by bavaleakashGL** [comment]
This is how I resolved it:
By default Angular does not allow **process** variable, you will need to add

**import * as process from 'process';
window['process'] = process;**

in **polyfills.ts** in order to enable it, after this it was a piece of cake. Thanks.
