### ISSUE TITLE
Support of Angular 14

### ISSUE THREAD

**Issue by pavel-romanov8** [chihab/ngx-env#18]
It would be great to add support of Angular 14 version since it was officially released by the Angular team

**Comment by chihab** [comment]
If you have an existing project <= v13 already working with ng-env/builder and you upgrade it to v14 it should work just fine.

If you create a new projet, `ng-add ngx-env/builder` won't work.. Here is a workaround to make it work:
- npm add ngx-env/builder (notice `npm` here)
- In `angular.json`, replace every occurence of `@angular-devkit/build-angular` by `@ngx-env/builder`
- Create a new file src/env.d.ts:
```
declare var process: {
    env: {
      NG_APP_ENV: string;
      // Replace the line below with your environment variable for better type checking
      [key: string]: any;
    };
  };
 ```
- Restart your CLI

That is what `ng add`. I am on it to make it compatible with v14.
