### ISSUE TITLE
Polyfills should be excluded from "expansion" process

### ISSUE THREAD

**Issue by JeffreyArt1** [chihab/ngx-env#38]
I think the polyfills should be excluded from the "expansion" process as they're not part of the application src.

```ts
process.env["NG_APP_PRETTY_CAR"];

// after build, turns into: 
{ NG_APP_PRETTY_CAR: "value", NG_APP_ENV: "production" }.NG_APP_PRETTY_CAR
```

The `reflect-metadata` polyfill has references to `process.env` in it's code. See [here](https://github.com/rbuckton/reflect-metadata/blob/3aeb98af4030be664a66f49bfd164936e0ba1825/Reflect.ts#L678)

**Comment by chihab** [comment]
I think they're technically part of the application: any logic you put in that file will end up in the browser.

If you put `process.env` in the fail and not replace with the builder it will fail at runtime, wouldn't it?
