### ISSUE TITLE
The order of environment variables are important for k8s pods

### ISSUE THREAD

**Issue by mostafa8026** [chihab/ngx-env#39]
I'm using this awesome package to inject environment variables into my web service. Everything works fine when we have one single pod in a k8s deployment, but when we have more than one pod, the production goes down. Why?
Because the hash of the `mian.hash.js` will be different for each pod (the codebase is the same). After investigating a lot, I've realized that this package injects the environment without alphabetically sorting them and it sometimes causes a random order and makes the main.js hash different.
To solve the issue I simply add the `.sort()` to the `plugin.ts` file. I will open a PR later.

NOTE: It is worth mentioning, I have an issue with the version of the `chalk` package. and the problem has been fixed by installing the `chalk` and then publishing the pcakge.

**Comment by chihab** [comment]
Thanks for reporting this issue @mostafa8026.
I am not familiar with k8s, I wanna be sure that I understand the issue: pods in a cluster are supposed to have the same environment variables values and you're using the pods to build and serve the app and when doing so you get different build outputs even though the entries are exactly the same, am I right?
So to reproduce the issue on my hand, I'd have to build the app multiple times and I might get different output hashes, right?

**Comment by mostafa8026** [comment]
Yes, you were right.
To reproduce the issue locally, I do these steps:

1- remove previous dist folder (and remove caches like nx caches if exists)
2- reorder the env variables inside the `.env` file.
3- build the project.
4- check the hash of the main.js to be just like before.
