### ISSUE TITLE
Problem with module federation

### ISSUE THREAD

**Issue by odflorezr** [chihab/ngx-env#50]
I have an error "Error: Schema validation failed with the following errors: Data path "" must NOT have additional properties(extraWebpackConfig)."

If delete all definitions for extraWebpack the module federation in angular 16 it corrupts and dont'n generate remoteEntry.js

--
My package.json is: 

  "dependencies": {
    "@angular-architects/module-federation": "^16.0.4",
    "@angular/animations": "^16.1.0",
    "@angular/cdk": "^16.1.3",
    "@angular/common": "^16.1.0",
    "@angular/compiler": "^16.1.0",
    "@angular/core": "^16.1.0",
    "@angular/forms": "^16.1.0",
    "@angular/material": "^16.1.3",
    "@angular/platform-browser": "^16.1.0",
    "@angular/platform-browser-dynamic": "^16.1.0",
    "@angular/router": "^16.1.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.1.1",
    "@angular/cli": "~16.1.1",
    "@angular/compiler-cli": "^16.1.0",
    "@ngx-env/builder": "^16.1.2",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "ngx-build-plus": "^16.0.0",
    "typescript": "~5.1.3"
  }

**Comment by chihab** [comment]
Hey, are you using another custom builder? Could you share your `angular.json`? or better a repo reproducing the issue?

**Comment by chihab** [comment]
Closing the issue. Feel free to re-open the issue with a reproducing project (preferrably on stackblitz).
