### ISSUE TITLE
I cannot access my environment variables in my environment.ts

### ISSUE THREAD

**Issue by FelixH15** [chihab/ngx-env#51]
I encountered an error while trying to build my Angular application. The specific error message is as follows:
`ERROR in ./src/environments/environment.ts 6:19
Module parse failed: Unexpected token (6:19)
You may need an appropriate loader to handle this file type.
>     baseURL: import.meta.env["BASE_URL"],
|     ssoURL: import.meta.env["SSO_URL"],
|     chatURL: import.meta.env["CHAT_URL"],`

Here's my environment.prod.ts code:
`export const environment = {
  production: true,
  baseURL: import.meta.env["BASE_URL"],
  ssoURL: import.meta.env["SSO_URL"],
  chatURL: import.meta.env["CHAT_URL"],
};`

I'm using angular 7

Thank you

**Comment by chihab** [comment]
Hey could you provide a repo that reproduces the issue?

**Comment by chihab** [comment]
Closing the issue. Feel free to re-open the issue with a reproducing project (preferrably on stackblitz).
