### ISSUE TITLE
environment variables not being set

### ISSUE THREAD

**Issue by scry-UrjitDesai** [chihab/ngx-env#55]
Hey, I am trying to use the library for something i am working on. I followed the steps listed but I cannot access the .env files and variables inside them. I tried to log the import.meta.env it says {NG_APP_ENV: undefined}

I used: `ng serve` which prints the following.
---------------------------------
- Verbose:  true
- Prefix:  NG_APP
- Root directory:  .
- Working directory:  /home/urjit.desai/Desktop/ABC/ABC-ui/client
- Environment files: 
 ✔ /home/urjit.desai/Desktop/ABC/ABC-ui/client/.env
- Injected keys:
 ✔ NG_APP_ENV => undefined
---------------------------------

I have my .env file at the package.json level here are its contents:

SERVER_URL=http://google.com
NUMBER_OF_FILES=10

I want to access them within my code but it gives me undefined.

**Comment by chihab** [comment]
Hey, you should use NG_APP prefix, so NG_APP_SERVER_URL and NG_APP_NUMBER_OF_FILES.

**Comment by scry-UrjitDesai** [comment]
Thanks, that solved it !
