### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by PR4SAN** [chihab/ngx-env#61]
With angular 17 this doesn't work and throws an error of
`Error: Schema validation failed with the following errors: Data path "" must have required property 'main'.`

**Comment by fsegurai** [comment]
Yeah, got same error

**Comment by chihab** [comment]
In angular.json


```diff
-"builder": "@angular-devkit/build-angular:application",
+"builder": "@ngx-env/builder:browser",
```

```diff
-"browser": "src/main.ts",
+"main": "src/main.ts",
```

![image](https://github.com/chihab/ngx-env/assets/196852/5a8da5d5-fdd1-4464-b2f7-028ee92350f9)

Let me know if that works for you please.

Note that it will use the webpack builder which @ngx-env/builder is built on top of.
There are still issues with using the esbuild plugins, once stable and enough documented, I'll release a new v17 compatible with vite and esbuild.

**Comment by fsegurai** [comment]
@chihab the workaround provided did the trick 😄 
Thanks for your time and assistance.  Look forward to the new version 🥇 👍🏼

**Comment by chihab** [comment]
Could you give `npx ng add @ngx-env/builder@17.0.0-alpha.0` a try?

**Comment by fsegurai** [comment]
@chihab I tested the command provided `npx ng add @ngx-env/builder@17.0.0-alpha.0` and no manual configuration nor further actions were required. I was able to use the environment variables 👍🏼 
The build architect target property in the `angular.json` file was automatically updated to `@ngx-env/builder:application`

**Comment by meteoiker** [comment]
The latest available version of @ngx-env/core is 16.1.3 depending on Angular 16. I also cannot see updated code in the repository so for the moment I cannot update to angular version 17 until this package is updated. Does this code need more work for Angular 17 support or is simply a dependency update?

**Comment by chihab** [comment]
@ngx-env/core@16 should work with Angular 17 but its peer dep indicates ^16 so you should have a peer dep missing issue but if you force, it should work, in theory.

Now, I would suggest not to use @ngx-env/core mainly because the good practice is not put the process.env in the template nor in the component code but rather reference it in your angular environment files (or any configuration file).

**Comment by meteoiker** [comment]
Thank you @chihab . I was using the env pipe and migrated everything as you said and removed the dependency. Everything works.
