### ISSUE TITLE
Conflict with block-scoped `@types/node` on `env.d.ts`

### ISSUE THREAD

**Issue by chernodub** [chihab/ngx-env#8]
Hi guys, thanks for your work! I was wondering how do you resolve the issue with overriding node-provided `process`? Also, the type definition is not checked by the compiler (since the file is not incuded into the `files` section of `tsconfig.app.json` for [multiproject structure](https://angular.io/guide/file-structure#multiple-projects)), is it intended only to be used by the IDE's autocomplete?

Environment:
Angular v13.0.0
@ngx-env/builder 2.0.0
![image](https://user-images.githubusercontent.com/37013688/142836172-1aa27295-4384-4688-929a-76ddfc0d7b74.png)

Thanks!

**Comment by chernodub** [comment]
Maybe it'll be useful for some people. I was able to resolve the issue by using TS' merge declaration. Although be aware as it won't fail in case there is no such property in your env file.
```ts
// <project_root>/env.d.ts

declare namespace NodeJS {

  /** Merge declaration with `process` in order to override the global-scoped env. */
  export interface ProcessEnv {

    /**
     * Built-in environment variable.
     * @see Docs https://github.com/chihab/ngx-env#ng_app_env.
     */
    readonly NG_APP_ENV: string;

    // Add your environment variables below 
    /** Test data. */
    readonly NG_APP_TITLE: string;
  }
}

```

**Comment by chihab** [comment]
Shouldn't the definition file below do it?
```
declare var process: {
  env: {
    NG_APP_ENV: string;
    NG_APP_TITLE: string;
  };
};
```

**Comment by chernodub** [comment]
The re-declaration is only on my IDE since the declaration file is not included in any of the applications in multiworkspace (by default). Anyway, your solution works great, thanks @chihab!

**Comment by stephane-tessier** [comment]
Hi

I have the same problem but I didn't understand the fix.

I have `src/env.d.ts`: 
```
declare let process: {
  env: {
    NG_APP_ENV: string;
    // Replace the line below with your environment variable for better type checking
    NG_APP_apiHost: string;
    NG_APP_apiURL: string;
  };
};
```

and when I run my linter: 
```sh
tsc --noEmit && eslint . --ext js,ts --quiet --fix
```

**"Cannot redeclare block-scoped variable 'process'."**

![image](https://user-images.githubusercontent.com/2227881/156405532-8a570e94-09c2-4ce3-bb37-12c77d036485.png)
